# Generated by Django 4.2.6 on 2023-10-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('product_image', models.FileField(upload_to='media/product/')),
                ('ingredients', models.TextField(max_length=3000)),
                ('nutrition_image', models.FileField(upload_to='media/nutrition/')),
            ],
        ),
    ]
